apiVersion: v1
kind: Service
metadata:
  name: pfe-ai-service
  namespace: pfe
spec:
  selector:
    app: pfe-ai-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
