apiVersion: v1
kind: Service
metadata:
  name: pfe-backend
  namespace: pfe
spec:
  selector:
    app: pfe-backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
