apiVersion: v1
kind: Service
metadata:
  name: pfe-frontend
  namespace: pfe
spec:
  selector:
    app: pfe-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
